// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhBnNlQydqBhPAgrBXe5X63BLmXHGFGss',
    appId: '1:1004379306847:web:ba76283fffbcf77665d4ea',
    messagingSenderId: '1004379306847',
    projectId: 'movieapp2-96ab3',
    authDomain: 'movieapp2-96ab3.firebaseapp.com',
    storageBucket: 'movieapp2-96ab3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyw5uegbOXAFpWS4-5S0s1MaSnnURd-Y',
    appId: '1:1004379306847:android:996f18951d989c7165d4ea',
    messagingSenderId: '1004379306847',
    projectId: 'movieapp2-96ab3',
    storageBucket: 'movieapp2-96ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hWWQgJcWZbb4lSylJmhHfoDqKrwJgyk',
    appId: '1:1004379306847:ios:5c183da998299c8365d4ea',
    messagingSenderId: '1004379306847',
    projectId: 'movieapp2-96ab3',
    storageBucket: 'movieapp2-96ab3.appspot.com',
    iosBundleId: 'com.example.movieAppExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9hWWQgJcWZbb4lSylJmhHfoDqKrwJgyk',
    appId: '1:1004379306847:ios:ed262e0a6163ceaa65d4ea',
    messagingSenderId: '1004379306847',
    projectId: 'movieapp2-96ab3',
    storageBucket: 'movieapp2-96ab3.appspot.com',
    iosBundleId: 'com.example.movieAppExample.RunnerTests',
  );
}
